---
title: "diabetes_regression"
format: html
editor: visual
---

## Run regression with HbA1c separately

```{r}
library(ggplot2)
diabetes_df <- read.csv("/Users/eunicegu/Linear Modeling/project/Diabetes Dataset/Dataset of Diabetes .csv")
head(diabetes_df)
```

```{r}
#change TG from categorical data to numerical
diabetes_df$TG <- as.numeric(diabetes_df$TG)
#change gender to dummy variable, F = 1, M = 0
diabetes_df$female <- ifelse(diabetes_df$Gender == "F", 1, 0)
# assign value to newly created NA 
indices_to_change <- which(is.na(diabetes_df$TG))
diabetes_df$TG[indices_to_change] <- 1.6
```

### HbA1c with AGE
```{r}
reg_1 <- lm(HbA1c ~ AGE, diabetes_df)
print(summary(reg_1))
```

```{r}
ggplot(diabetes_df) + 
  geom_point(aes(y = HbA1c, x = AGE), size = 1) +
  theme(axis.text = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 10))
```

```{r}
ggplot(diabetes_df) + 
    geom_density_2d_filled(aes(y=HbA1c, x=AGE)) +
    theme(axis.text = element_text(size = 8), 
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=AGE)) +
    geom_line(aes(x=AGE, y=reg_1$fitted.values), color="red", 
    linewidth=1) +
    theme(axis.text = element_text(size = 8), 
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10))
```
```{r}
dens <- kde2d(diabetes_df$AGE, diabetes_df$HbA1c)
p <- plot_ly(z = ~dens$z) %>%
  add_surface(x = dens$x, y = dens$y) 
p <- p %>% layout(scene = list(xaxis = list(title = "AGE"),
                                yaxis = list(title = "HbA1c"),
                                zaxis = list(title = "Density")))
p
```
### HbA1c with Urea
```{r}
reg_2 <- lm(HbA1c ~ Urea, diabetes_df)
print(summary(reg_2))
```

```{r}
ggplot(diabetes_df) + geom_point(aes(y=HbA1c, x=Urea))
```

```{r}
ggplot(diabetes_df) + geom_density_2d_filled(aes(y=HbA1c, x=Urea))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=Urea)) +
    geom_line(aes(x=Urea, y=reg_2$fitted.values), color="red", linewidth=2)
```

### HbA1c with Cr
```{r}
reg_3 <- lm(HbA1c ~ Cr, diabetes_df)
print(summary(reg_3))
```

```{r}
ggplot(diabetes_df) + geom_point(aes(y=HbA1c, x=Cr))
```

```{r}
ggplot(diabetes_df) + geom_density_2d_filled(aes(y=HbA1c, x=Cr))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=Cr)) +
    geom_line(aes(x=Cr, y=reg_3$fitted.values), color="red", linewidth=2)
```

### HbA1c with Chol
```{r}
reg_4 <- lm(HbA1c ~ Chol, diabetes_df)
print(summary(reg_4))
```

```{r}
ggplot(diabetes_df) + geom_point(aes(y=HbA1c, x=Chol))
```

```{r}
ggplot(diabetes_df) + geom_density_2d_filled(aes(y=HbA1c, x=Chol))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=Chol)) +
    geom_line(aes(x=Chol, y=reg_4$fitted.values), color="red", linewidth=2)
```

### HbA1c with TG
```{r}
reg_5 <- lm(HbA1c ~ TG, diabetes_df)
print(summary(reg_5))
```

```{r}
ggplot(diabetes_df) + geom_point(aes(y=HbA1c, x=TG))
```

```{r}
ggplot(diabetes_df) + geom_density_2d_filled(aes(y=HbA1c, x=TG))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=TG)) +
    geom_line(aes(x=TG, y=reg_5$fitted.values), color="red", linewidth=2)
```

### HbA1c with HDL
```{r}
reg_6 <- lm(HbA1c ~ HDL, diabetes_df)
print(summary(reg_6))
```

```{r}
ggplot(diabetes_df) + geom_point(aes(y=HbA1c, x=HDL))
```

```{r}
ggplot(diabetes_df) + geom_density_2d_filled(aes(y=HbA1c, x=HDL))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=HDL)) +
    geom_line(aes(x=HDL, y=reg_6$fitted.values), color="red", linewidth=2)
```

### HbA1c with LDL
```{r}
reg_7 <- lm(HbA1c ~ LDL, diabetes_df)
print(summary(reg_7))
```

```{r}
ggplot(diabetes_df) + geom_point(aes(y=HbA1c, x=LDL))
```

```{r}
ggplot(diabetes_df) + geom_density_2d_filled(aes(y=HbA1c, x=LDL))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=LDL)) +
    geom_line(aes(x=LDL, y=reg_7$fitted.values), color="red", linewidth=2)
```

### HbA1c with VLDL
```{r}
reg_8 <- lm(HbA1c ~ VLDL, diabetes_df)
print(summary(reg_8))
```

```{r}
ggplot(diabetes_df) + geom_point(aes(y=HbA1c, x=VLDL))
```

```{r}
ggplot(diabetes_df) + geom_density_2d_filled(aes(y=HbA1c, x=VLDL))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=VLDL)) +
    geom_line(aes(x=VLDL, y=reg_8$fitted.values), color="red", linewidth=2)
```

### HbA1c with BMI
```{r}
reg_9 <- lm(HbA1c ~ BMI, diabetes_df)
print(summary(reg_9))
```

```{r}
ggplot(diabetes_df) + 
  geom_point(aes(y = HbA1c, x = BMI), size = 1) +
  theme(axis.text = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 10)) 
```

```{r}
ggplot(diabetes_df) +
  geom_density_2d_filled(aes(y=HbA1c, x=BMI)) +
  theme(axis.text = element_text(size = 8), 
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=BMI)) +
    geom_line(aes(x=BMI, y=reg_9$fitted.values), color="red", 
    linewidth=1) +
    theme(axis.text = element_text(size = 8), 
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10))
```
```{r}
dens <- kde2d(diabetes_df$BMI, diabetes_df$HbA1c)
p <- plot_ly(z = ~dens$z) %>%
  add_surface(x = dens$x, y = dens$y) 

p <- p %>% layout(scene = list(xaxis = list(title = "BMI"),
                                yaxis = list(title = "HbA1c"),
                                zaxis = list(title = "Density")))
p
```
### HbA1c with female
```{r}
reg_10 <- lm(HbA1c ~ female, diabetes_df)
print(summary(reg_10))
```

```{r}
ggplot(diabetes_df) + 
  geom_point(aes(y = HbA1c, x = female), size = 1) +
  theme(axis.text = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 10)) 
```

```{r}
ggplot(diabetes_df) +
  geom_density_2d_filled(aes(y=HbA1c, x=female)) +
  theme(axis.text = element_text(size = 8), 
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10))
```

```{r}
ggplot(diabetes_df) +
    geom_density_2d_filled(aes(y=HbA1c, x=female)) +
    geom_line(aes(x=female, y=reg_10$fitted.values), color="red", 
    linewidth=1) +
    theme(axis.text = element_text(size = 8), 
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10))
```
```{r}
dens <- kde2d(diabetes_df$female, diabetes_df$HbA1c)
p <- plot_ly(z = ~dens$z) %>%
  add_surface(x = dens$x, y = dens$y) 
p <- p %>% layout(scene = list(xaxis = list(title = "female"),
                                yaxis = list(title = "HbA1c"),
                                zaxis = list(title = "Density")))
p
```
